# Generated by Django 5.2.6 on 2025-11-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal (R)'), ('teacher', 'Teacher (S)'), ('admin', 'Admin (A)')], default='normal', max_length=20),
        ),
    ]
