# Generated by Django 5.2.6 on 2025-12-13 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olimpiade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosaukums', models.CharField(max_length=100)),
                ('datums', models.DateField()),
                ('maxDalibnieki', models.IntegerField(blank=True, null=True)),
                ('apraksts', models.CharField(blank=True, max_length=250, null=True)),
                ('norisesVieta', models.CharField(max_length=100)),
                ('organizetajs', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Olimpiāde',
                'verbose_name_plural': 'Olimpiādes',
                'db_table': 'Olimpiades',
            },
        ),
        migrations.CreateModel(
            name='Prieksmets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosaukums', models.CharField(max_length=50)),
                ('kategorija', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Priekšmets',
                'verbose_name_plural': 'Priekšmeti',
                'db_table': 'Prieksmeti',
            },
        ),
        migrations.CreateModel(
            name='Skola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosaukums', models.CharField(max_length=50)),
                ('pasvaldiba', models.CharField(blank=True, max_length=50, null=True)),
                ('adrese', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Skola',
                'verbose_name_plural': 'Skolas',
                'db_table': 'Skolas',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Konts', 'verbose_name_plural': 'Konti'},
        ),
        migrations.AddField(
            model_name='user',
            name='izveidosanasDatums',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='talrNumurs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tips',
            field=models.CharField(default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='uzvards',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vards',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Konti',
        ),
        migrations.CreateModel(
            name='Pieteikums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuss', models.CharField(max_length=50)),
                ('pieteikumaDatums', models.DateField(auto_now_add=True)),
                ('lietotajs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieteikumi', to=settings.AUTH_USER_MODEL)),
                ('olimpiade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieteikumi', to='api.olimpiade')),
            ],
            options={
                'verbose_name': 'Pieteikums',
                'verbose_name_plural': 'Pieteikumi',
                'db_table': 'Pieteikumi',
            },
        ),
        migrations.AddField(
            model_name='olimpiade',
            name='pieteikums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olimpiades_pieteikums', to='api.pieteikums'),
        ),
        migrations.AddField(
            model_name='olimpiade',
            name='prieksmets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olimpiades', to='api.prieksmets'),
        ),
        migrations.CreateModel(
            name='Rezultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punktuSkaits', models.FloatField()),
                ('vieta', models.IntegerField()),
                ('rezultataDatums', models.DateField()),
                ('lietotajs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rezultati', to=settings.AUTH_USER_MODEL)),
                ('olimpiade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezultati', to='api.olimpiade')),
            ],
            options={
                'verbose_name': 'Rezultāts',
                'verbose_name_plural': 'Rezultāti',
                'db_table': 'Rezultati',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='skola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lietotaji', to='api.skola'),
        ),
        migrations.CreateModel(
            name='SkolasStarp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olimpiades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skolas', to='api.olimpiade')),
                ('skolas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olimpiades', to='api.skola')),
            ],
            options={
                'verbose_name': 'Skola-Olimpiāde',
                'verbose_name_plural': 'Skolas-Olimpiādes',
                'db_table': 'SkolasStarp',
                'unique_together': {('skolas', 'olimpiades')},
            },
        ),
    ]
