# Generated by Django 5.2.6 on 2026-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_olimpiade_prieksmets_skola_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skola',
            name='nosaukums',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='skola',
            index=models.Index(fields=['nosaukums'], name='skolas_nosaukums_idx'),
        ),
    ]
