# Generated by Django 5.2.6 on 2026-01-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_school_search_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='skola',
            name='skolas_nosaukums_idx',
        ),
        migrations.AlterField(
            model_name='skola',
            name='nosaukums',
            field=models.CharField(max_length=50),
        ),
    ]
